create table if not exists public.premium_credits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 100 check (balance >= 0),
  lifetime_earned integer not null default 100 check (lifetime_earned >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.premium_credit_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delta integer not null,
  reason text not null default 'adjustment',
  created_at timestamptz not null default now()
);

alter table public.premium_credits enable row level security;
alter table public.premium_credit_transactions enable row level security;

drop policy if exists "Users can read own credits" on public.premium_credits;
create policy "Users can read own credits"
on public.premium_credits for select
using (auth.uid() = user_id);

drop policy if exists "Users can read own credit transactions" on public.premium_credit_transactions;
create policy "Users can read own credit transactions"
on public.premium_credit_transactions for select
using (auth.uid() = user_id);

create or replace function public.set_premium_credits_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists premium_credits_updated_at on public.premium_credits;
create trigger premium_credits_updated_at
before update on public.premium_credits
for each row execute function public.set_premium_credits_updated_at();

insert into public.premium_credits (user_id)
select id from auth.users
on conflict (user_id) do nothing;
